### ISSUE TITLE
Domain.FindPlan(...) rejects valid new plan

### ISSUE THREAD

**Issue by Emelion1** [ptrefall/fluid-hierarchical-task-network#12] opened 2022-09-29 16:42 UTC
**Describe the bug**
 `Domain.FindPlan(...)` rejects valid new plan, because the `MethodTraversalRecord` equals the `LastMTR`, even though the found plan differs from the last found plan.

**To Reproduce**
Define a domain like this (where `OperatorA` and `OperatorB` are both operators that do NOT finish instantly):

```
.Select("Test Select")
    .Action("Test Action A")
        .Condition("Can choose A", ctx => ctx.HasState(TestWorldState.CanChooseA))
        .SetOperator(new OperatorA())
    .End()

    .Action("Test Action B")
        .Condition("Can not choose A", ctx => !ctx.HasState(TestWorldState.CanChooseA))
        .SetOperator(new OperatorB())
    .End()
.End()
```

Then set `TestWorldState.CanChooseA` to `true` and `Tick()` the planer. Observe (as expected) that a plan containing only "Test Action A" is found.
Then (while the existing plan is not yet finished) set `TestWorldState.CanChooseA` to `false` and `Tick()` the planer again. Observe that the plan containing only "Test Action B" is initially found during the decomposition but is then discarded by this part of the code:

```
// If this MTR equals the last MTR, then we need to double check whether we ended up
// just finding the exact same plan. During decomposition each compound task can't check
// for equality, only for less than, so this case needs to be treated after the fact.
var isMTRsEqual = ctx.MethodTraversalRecord.Count == ctx.LastMTR.Count;
if (isMTRsEqual)
{
    for (var i = 0; i < ctx.MethodTraversalRecord.Count; i++)
        if (ctx.MethodTraversalRecord[i] < ctx.LastMTR[i])
        {
            isMTRsEqual = false;
            break;
        }

    if (isMTRsEqual)
    {
        plan = null;
        status = DecompositionStatus.Rejected;
    }
}
```

because both the `MethodTraversalRecord` and the `LastMTR` are equal and contain only the single entry `0`, even though the new plan (containing only "Test Action B") is different from the old plan (containing only "Test Action A").

**Expected behavior**
The new plan should not have been rejected for being equal to the old plan because it is clearly different.

**Comment by ptrefall** [comment] 2022-09-29 17:14
Thank you! I will investigate this issue 😊

**Comment by ptrefall** [comment] 2022-09-30 11:49
Yes, this points to an issue where MTR at the moment only tracks compound tasks. From the unit test in DomainTests:
`FindPlanIfMTRsAreEqualThenReturnNullPlan_ExpectedBehavior` we can see the comment here read:

> // Root is a Selector that branch off into task1 selector or task2 sequence.
            // MTR only tracks decomposition of compound tasks, so our MTR is only 1 layer deep here,
            // Since both compound tasks decompose into primitive tasks.

This is clearly undesired in your use case (and I'm sure in other use cases as well). I don't recall exactly why this limitation was put in, so I will have to do some research into my code and Troy's article that I based the project on to see if there's a clear path towards a good solution that doesn't break existing desired behavior.

**Comment by Emelion1** [comment] 2022-09-30 13:34
Thanks for looking into this. Let me know if you need more information or found a solution.

While I thought about how to solve this problem myself, my first guess was to also track primitive tasks in the MTR (at least when they are decomposed from a selector), but I am not really sure what the unexpected side effects of that might be.

**Comment by ptrefall** [comment] 2022-09-30 18:27
Please review my change proposal and whether it meets the issue raised here @Emelion1. Does this fully resolve your issue? Please verify that the new Domain test fully represents the issue you raised:
`FindPlanIfSelectorFindBetterPrimaryTaskMTRChangeSuccessfully_ExpectedBehavior`

**Comment by Emelion1** [comment] 2022-10-05 19:18
I am sick at the moment. I will review your changes next week when I am feeling better. But thanks for your help already.

**Comment by ptrefall** [comment] 2022-10-09 17:12
Get well soon! 😊

**Comment by Emelion1** [comment] 2022-10-12 12:37
Hey, I downloaded and tested your changes and unfortunately it does not work for my testcase yet.

In the same example I gave in my original issue-description the second plan containing only "Test Action B" (that was previously found by the planner but then rejected because of the identical MTR) is now rejected during planning in `Selector.OnDecompose(...)` by this piece of code
```
if (BeatsLastMTR(ctx, taskIndex, currentDecompositionIndex) == false)
{
    ctx.MethodTraversalRecord.Add(-1);
    if (ctx.DebugMTR) ctx.MTRDebug.Add($"REPLAN FAIL {Subtasks[taskIndex].Name}");

    if (ctx.LogDecomposition)
        Log(ctx,
            $"Selector.OnDecompose:Rejected:Index {currentDecompositionIndex} is beat by last method traversal record!", ConsoleColor.Red);
    result = null;
    return DecompositionStatus.Rejected;
}
```
before it can even reach the piece of code that previously rejected it.

**Comment by ptrefall** [comment] 2022-10-13 10:20
> Hey, I downloaded and tested your changes and unfortunately it does not work for my testcase yet.
> 
> In the same example I gave in my original issue-description the second plan containing only "Test Action B" (that was previously found by the planner but then rejected because of the identical MTR) is now rejected during planning in `Selector.OnDecompose(...)` by this piece of code
> 
> ```
> if (BeatsLastMTR(ctx, taskIndex, currentDecompositionIndex) == false)
> {
>     ctx.MethodTraversalRecord.Add(-1);
>     if (ctx.DebugMTR) ctx.MTRDebug.Add($"REPLAN FAIL {Subtasks[taskIndex].Name}");
> 
>     if (ctx.LogDecomposition)
>         Log(ctx,
>             $"Selector.OnDecompose:Rejected:Index {currentDecompositionIndex} is beat by last method traversal record!", ConsoleColor.Red);
>     result = null;
>     return DecompositionStatus.Rejected;
> }
> ```
> 
> before it can even reach the piece of code that previously rejected it.

Hm, weird. Could you send me a copy of your test-case? From what I can tell from the snippets you have pasted, the FindPlanIfSelectorFindBetterPrimaryTaskMTRChangeSuccessfully_ExpectedBehavior test should have covered your use case. If you'd be able to create a domain unit test that could reproduce your issue it would be amazing, but I can make one based on your project files as well if I get access.

**Comment by Emelion1** [comment] 2022-10-17 13:32
[HtnTest.zip](https://github.com/ptrefall/fluid-hierarchical-task-network/files/9800910/HtnTest.zip)

Here I have attached my test ("MyHtnOperatorTest.cs") and the supporting classes to make it work. It should work if you put the contents of the zip-file into the "Assets/Code"-folder of a fresh Unity-project (I am using Unity 2022.1.11f1) and also include FluidHTN in this project.

The version I have send you here is not really using any test framework but you can easily convert it to use a test-framework of your choice or even test it without one like this:

```
MyHtnOperatorTest test = new MyHtnOperatorTest();

test.OnSetup();
test.TestOperatorFlowFinishedNormally();
test.OnTearDown();

test.OnSetup();
test.TestOperatorFlowAborted();
test.OnTearDown();
```

The wrong behaviour (not finding the plan containing only the action "Test Action No Logging") happens in the `_planner.Tick(_domain, _context, true);` on line 196 of `MyHtnOperatorTest` in `TestOperatorFlowAborted()` and is noticed by the `Assert.AreEqual(1, _context.EndCount);` on line 200 since the planner did not find the new plan and so did not end the old plan (containing only "Test Action Logging").

**Comment by ptrefall** [comment] 2022-10-17 20:43
Thank you! I will check this out ASAP 😊

**Comment by Emelion1** [comment] 2022-10-24 06:49
Thanks! Let me know when you have any news about this.

**Comment by ptrefall** [comment] 2022-10-27 07:45
Yes, sorry for the delay. It has been an extremely busy week. I hope to get to it this weekend.

**Comment by Emelion1** [comment] 2022-11-15 08:31
Any updates?

**Comment by ptrefall** [comment] 2022-12-02 09:20
Hi again @Emelion1 and sorry for the MIA. Your provided code example had just enough custom changes to it (which I love btw), that I haven't been able to do a quick test on it just yet. I really need to rewrite it into a test that will reproduce the problem reliably in the base project, so that I can properly fix it and have proof of the fix. If you would be interested in providing such a test to reproduce the problem it would certainly save me some work, but I will get around to it, I'm just very busy so I've struggled to find enough time to set aside for this yet.

**Comment by Emelion1** [comment] 2022-12-05 11:54
Ok, great. I hope you get around to it soon. Unfortunately I do currently not have a version of the test that works without my extensions so I can not easily provide such a test for you.

**Comment by ptrefall** [comment] 2022-12-05 12:01
Yeah, understandable. It would be great to get a confirmation there whether the implementation I did is what fails and my test that is passing when it shouldn't (e.g. it's not doing sufficient checks to prove it works, or doesn't work), or whether there is something particular to your extensions. So let's see who gets to it first then.

**Comment by Emelion1** [comment] 2022-12-20 09:57
Here, I modified your test to be able to reproduce the problem without needing my extensions:

```
private class MyOperator : IOperator
{
    public TaskStatus Update(IContext ctx)
    {
        return TaskStatus.Continue;
    }

    public void Stop(IContext ctx)
    {
    }
}

[TestMethod]
public void FindPlanIfSelectorFindBetterPrimaryTaskMTRChangeSuccessfully_ExpectedBehavior()
{
    var ctx = new MyContext();
    ctx.Init();

    var planner = new Planner<MyContext>();
    var domain = new Domain<MyContext>("Test");
    var select = new Selector() { Name = "Test Select" };

    var actionA = new PrimitiveTask() { Name = "Test Action A" };
    actionA.AddCondition(new FuncCondition<MyContext>("Can choose A", context => context.Done == true));
    actionA.SetOperator(new MyOperator());
    var actionB = new PrimitiveTask() { Name = "Test Action B" };
    actionB.AddCondition(new FuncCondition<MyContext>("Can not choose A", context => context.Done == false));
    actionB.SetOperator(new MyOperator());

    domain.Add(domain.Root, select);
    domain.Add(select, actionA);
    domain.Add(select, actionB);

    Queue<ITask> plan;
    ITask currentTask;

    planner.Tick(domain, ctx, false);
    plan = planner.GetPlan();
    currentTask = planner.GetCurrentTask();
    Assert.IsTrue(plan != null);
    Assert.IsTrue(plan.Count == 0);
    Assert.IsTrue(currentTask.Name == "Test Action B");
    Assert.IsTrue(ctx.MethodTraversalRecord.Count == 2);
    Assert.IsTrue(ctx.MethodTraversalRecord[0] == 0);
    Assert.IsTrue(ctx.MethodTraversalRecord[1] == 1);

    // When we change the condition to Done = true, we should now be able to find a better plan!
    ctx.Done = true;

    planner.Tick(domain, ctx, true);
    plan = planner.GetPlan();
    currentTask = planner.GetCurrentTask();
    Assert.IsTrue(plan != null);
    Assert.IsTrue(plan.Count == 0);
    Assert.IsTrue(currentTask.Name == "Test Action A");
    Assert.IsTrue(ctx.MethodTraversalRecord.Count == 2);
    Assert.IsTrue(ctx.MethodTraversalRecord[0] == 0);
    Assert.IsTrue(ctx.MethodTraversalRecord[1] == 0);
}
```

**Comment by ptrefall** [comment] 2022-12-20 10:23
Awesome! Thank you, I'll have a look right away!

**Comment by ptrefall** [comment] 2022-12-20 10:57
Please evaluate the changes in my latest commit to the branch and consider whether you think this completes the Pull Request to a satisfactory level to meet your problems @Emelion1. If so, please consider approving the pull request.

Your contributions helped me fix two issues. First the MTR issue that the PR set out to fix, which is proved by the first test I wrote, and second the test you provided pointed to another problem, which is the following:
When a primitive task's operator is continuous and the condition is validated by non-worldstate data (changing ctx.Done doesn't flag the world state dirty), then the planner has no way of knowing something changed. We do have support in code for non-worldstate data in conditions, but it requires the use of the [Executing Conditions](https://github.com/ptrefall/fluid-hierarchical-task-network#conditions). I realize that **Executing Conditions** probably needs improved documentation to emphasize the use-case where it's needed. By using an Executing Condition in this case, when we have a valid current task, we will check all executing codition for runtime validity every planner tick, and if it fails we issue a replan. However, the code as it were didn't issue an immediate replan as expected when setting the immediate replan flag to true. This is now fixed in the latest commit to this branch / PR, which resolves your test and it now passes successfully. 

So as it happens your issue was not due to the bug in MTR, but due to insufficient documentation and thus understanding of Conditions vs Executing Conditions. Happy accident that you got to point out two bugs at the same time!

https://github.com/ptrefall/fluid-hierarchical-task-network/pull/13/commits/f4cb33e34aa2389faf5acb002471e7c3b9102da5

**Comment by ptrefall** [comment] 2022-12-20 11:18
I extended the documentation on Conditions with the following sub-section:

> **Executing Conditions**
> Advanced: Executing Conditions are special conditions that are evaluted every planner tick. These are only required if you have conditions that does not evaluate its validity based on world state entries, but instead based on other data in the runtime Context. The planner knows when world state has become dirty, but will not know when non-worldstate has changed, and this is where Executing Conditions come in. If an Executing Consition fail for the currently executing task, it will invalidate the running plan and require a replan.

Let me know if you think this needs improvement to fully get every point across. And thank you for your time and efforts to resolve the issues addressed @Emelion1 !

**Comment by Emelion1** [comment] 2022-12-20 11:38
In my original test-case the condition I am changing IS a WorldState (`TestWorldState.LogOperations`). Is it still necessary to specify the condition that checks this WorldState as both a normal-Condition and an ExecutingCondition? Because that seems a bit unexpected to me.

**Comment by ptrefall** [comment] 2022-12-20 11:46
Hm, I'll write a test to verify.

**Comment by ptrefall** [comment] 2022-12-20 12:11
I wrote another test to verify, and when we use world state instead it triggers the new MTR fixes and indeed verifies that those fixes work as intended. The test passes. Please evaluate the test here @Emelion1 :
https://github.com/ptrefall/fluid-hierarchical-task-network/pull/13/commits/a6ecd2b6a2c7ae0884702b1a16c3db02f1376b3d

**Comment by Emelion1** [comment] 2022-12-20 12:12
I will have a look.

**Comment by Emelion1** [comment] 2022-12-20 12:16
Hmm. Your test passes but my test still fails... I will investigate what the remaining difference is.

**Comment by ptrefall** [comment] 2022-12-20 12:31
We're making progress!

**Comment by Emelion1** [comment] 2022-12-20 12:43
Ah, I found the conceptual difference:
In my test it is the other way around:

Initially the WorldState is set in a way that the "better"/first Action is chosen, then the WorldState changes so that the first Action is no longer allowed and the "worse"/second Action should be chosen instead.

If you change your test like this, you can see it for yourself:
```
public void FindPlanIfWorldStateChangeAndOperatorIsContinuous_ExpectedBehavior()
{
    var ctx = new MyContext();
    ctx.Init();

    var planner = new Planner<MyContext>();
    var domain = new Domain<MyContext>("Test");
    var select = new Selector() { Name = "Test Select" };

    var actionA = new PrimitiveTask() { Name = "Test Action A" };
    actionA.AddCondition(new FuncCondition<MyContext>("Can choose A", context => context.GetState(MyWorldState.HasA) == 0));
    actionA.SetOperator(new MyOperator());
    var actionB = new PrimitiveTask() { Name = "Test Action B" };
    actionB.AddCondition(new FuncCondition<MyContext>("Can not choose A", context => context.GetState(MyWorldState.HasA) == 1));
    actionB.SetOperator(new MyOperator());

    domain.Add(domain.Root, select);
    domain.Add(select, actionA);
    domain.Add(select, actionB);

    Queue<ITask> plan;
    ITask currentTask;

    planner.Tick(domain, ctx, false);
    plan = planner.GetPlan();
    currentTask = planner.GetCurrentTask();
    Assert.IsTrue(plan != null);
    Assert.IsTrue(plan.Count == 0);
    Assert.IsTrue(currentTask.Name == "Test Action A");
    Assert.IsTrue(ctx.MethodTraversalRecord.Count == 2);
    Assert.IsTrue(ctx.MethodTraversalRecord[0] == 0);
    Assert.IsTrue(ctx.MethodTraversalRecord[1] == 0);

    // When we change the condition to Done = true, the first plan should no longer be allowed, we should find the second plan instead!
    ctx.SetState(MyWorldState.HasA, true, EffectType.Permanent);

    planner.Tick(domain, ctx, true);
    plan = planner.GetPlan();
    currentTask = planner.GetCurrentTask();
    Assert.IsTrue(plan != null);
    Assert.IsTrue(plan.Count == 0);
    Assert.IsTrue(currentTask.Name == "Test Action B");
    Assert.IsTrue(ctx.MethodTraversalRecord.Count == 2);
    Assert.IsTrue(ctx.MethodTraversalRecord[0] == 0);
    Assert.IsTrue(ctx.MethodTraversalRecord[1] == 1);
}
```

**Comment by ptrefall** [comment] 2022-12-20 13:25
Very nice test! You have indeed reached some fairly advanced corner cases of HTN with your work @Emelion1 ! So, in this case you need to rely on Executing Conditions again. The reason for this is that we only consider the Condition of a task during planning and when it's popped off the plan stack. After this we rely entirely on Operator status results (e.g. the Operator could instaed of returning Continue evaluate the condition and return Failure to prevent the task from continuing), or you can rely on an Executing Condition that will re-evaluate the condition for every planner tick.

So what happens in your situation is that first it picks A, and the MTR record is [0, 0], then you make a world state change that flags the worldstate dirty. At this point is doesn't "detect" that the task is no longer valid, because the operator nor the executing conditions is flagging it as such. So it starts to look for a plan that can beat the running plan, and of course it can't, and it rejects the replan attempt as expected.

So, the solution to this issue is simply to either let the Operator return failure when it detects that you're in an unsupported state for the task/operation, or rely on Executing Conditions to detect the change to invalid state.

This should fix the issues, I'm pretty confident of that @Emelion1, but please verify. 

I will update the documentation to be a bit clearer in this regard. Indeed you hit a particular corner case here with how your test was set up, and trying to find out why has been a really interesting journey. Thank you again!

And here are the changes I made to your test to make it pass:
https://github.com/ptrefall/fluid-hierarchical-task-network/pull/13/commits/d6170c236afd45b29e1744bd12a3db5dc8fc8d94

**Comment by Emelion1** [comment] 2022-12-20 13:42
Ok that is a bit sad to hear, but if that is how it is intended to work, then the issue is resolved. At least I am glad, that we found the time to figure this out today together, and that I helped you find two actual issues in the process.

**Closed as completed** 2022-12-20 13:57 UTC

**Comment by ptrefall** [comment] 2022-12-20 14:12
This is indeed how it must work. In a lot of cases the very execution of a task will invalidate its own start condition, e.g. move from a to b, so there has to be a difference. Naming could possibly be improved to emphasise this, but I stuck to the conventions established by Humphreys.

**Comment by ptrefall** [comment] 2022-12-20 14:13
And thank you again for your contributions!

**Comment by Emelion1** [comment] 2022-12-20 14:37
I have a clarifying question about what you just said:

> In a lot of cases the very execution of a task will invalidate its own start condition, e.g. move from a to b, so there has to be a difference.

If this is the consideration you are making, would this not also be the problem when the new found Plan is better?

Because right now we have established the following "intended" behavior:
- 1. There is a running plan.
- 2. The WorldState changes.
- 3. This triggers a re-plan.
- 4. If the new found plan is better than the current plan, the current plan is aborted and the new one is started. Otherwise the current plan continues running, even if its conditions are not fulfilled anymore.

Is that consistent with what you just described the intended behavior to be?

**Comment by ptrefall** [comment] 2022-12-20 14:50
I would say so, yes. There is a difference between the initial required conditions under which a plan is formed and the conditions that validates whether the plan should continue to run or not. In my own implementations I think it's cleaner to just treat conditions as the conditions required for the plan to be formed, and possibly for each task of the plan to start executing, while I prefer to use the result state of the Operator to cause a runtime Failure condition, where at the point of task execution it's now the Operator's job to define whether the task should continue to run, whether it has successfully completed, or whether it Failed to complete. Executing Conditions are there to give the option of validating conditions on each planner tick, but it is indeed clearer if this rejecting of execution is given to the Operator, at least in the cases I've come across so far.

So I would say that the reason why you stumble on this logical error in your planning is because the planner sees your conditions as valid when the plan was formed, and your operator just continues forever. So there is no mechanism to say that the task is now invalid. So to the system the task is not invalid, it's very much valid, because the operator is returning that the task should continue, and there are now executing conditions to say otherwise. I do see where this can cause some confusion, and specially in a test case where the naming conventions and use-cases are quite abstract. I do find this becomes clearer when dealing with more real cases, though I'm sure it won't be clear in every situation.

**Comment by Emelion1** [comment] 2022-12-20 14:55
Ok.

One more thing:

Would it be correct to add:
```
(_currentTask as IPrimitiveTask)?.Stop(ctx);
```
to the code block that handles the `if (condition.IsValid(ctx) == false)`-case when checking the `ExecutingConditions`?

Because right now it just sets `_currentTask = null;` without calling `Stop(...)` which seems wrong to me.

**Comment by ptrefall** [comment] 2022-12-20 15:05
Hm, currently we only call stop on planner Reset and when a plan is replaced and there's a current task running. I'm slightly concerned these are different use-cases from when a task is invalidated/fails. Maybe adding a new OnFailure or Abort function would be better here? I would say that there are two cases where we could consider calling this function. When an operator returns Failure and when an executing condition fails. What do you think? This is of course in addition to the OnCurrentTaskFailed and OnCurrentTaskExecutingConditionFailed callbacks, but those are more intended for external subscription and not internal "reaction", so I think you're making a valid case here. Let me think about it a bit, and I'll set up a new PR for this (whether I call Stop or OnFailed/Abandon/Rejected/SomethingElse). I'm open to suggestions here.

**Comment by Emelion1** [comment] 2022-12-20 15:20
Maybe as an additional info so you can see where I am coming from:

As you could probably see from the code-sample I send you a few posts ago, I am trying to establish the following pattern on top of what you planner is currently doing:
- Every Operator has a "`Start()`", "`Update()`", "`End()`" and "`Abort()`" functions and makes sure they are called consistently.
- The first time a new Operator is executed, first "Start()" is called, then "Update()"
- Every further execution only "Update()" is called.
- When an operator, that was successfully started, ends "unwillingly" (because of external reasons like the Planner is reset or replaces the plan or rejects the operator for any other reason), first "Abort()" is called, then "End()" is called.
- When an operator, that was successfully started, ends "willingly" (because its "Update()" returned something other than `TaskStatus.Continue`) only "End()" is called.

This is almost working already but to make it work 100% I need to make sure I definitely get notified EVERY time an Operator gets ended "unwillingly" (and the case where it gets removed because of its ExecutingConditions is one where I am currently not getting notified).

**Comment by Emelion1** [comment] 2022-12-20 15:26
What changes I am currently trying (in `Planner.cs`) to get around this:

```
bool didDequeueNewTask = false;
if (_currentTask == null && _plan.Count > 0)
{
    _currentTask = _plan.Dequeue();
    didDequeueNewTask = true;

    ...
}

if (_currentTask != null)
    if (_currentTask is IPrimitiveTask task)
    {
        if (task.Operator != null)
        {
            foreach (var condition in task.ExecutingConditions)
                // If a condition failed, then the plan failed to progress! A replan is required.
                if (condition.IsValid(ctx) == false)
                {
                    ...

                    if (!didDequeueNewTask)
                    {
                        task.Stop(ctx);
                    }
                    _currentTask = null;
                    ...
                }

            ...
        }
        else
        {
            // This should not really happen if a domain is set up properly.
            if (!didDequeueNewTask)
            {
                task.Stop(ctx);
            }
            _currentTask = null;
            ...
        }
    }

...```

**Comment by Emelion1** [comment] 2022-12-20 15:28
I feel like I need this `didDequeueNewTask`-variable because the operator should only be stopped if it was already started...

**Comment by Emelion1** [comment] 2022-12-20 17:46
I now made sure `IPrimitiveTask.Stop(...)` (and also `OnStopCurrentTask?.Invoke(primitiveTask)`) is called every time an `IPrimitiveTask` is ended unwillingly and it worked for me.

But I now did some pretty significant refactoring of Planner.cs to be able to understand and modify the code easier, so this is probably not a change you can/want to just take for your Repository.

Here it is if you want to have a look anyways:
[Planner.zip](https://github.com/ptrefall/fluid-hierarchical-task-network/files/10270902/Planner.zip)

This will of course make it pretty difficult to get further updates from this repo in the future, but unless I notice any more issues, I will probably stay on this version.

Thanks for your support and good luck.

**Comment by ptrefall** [comment] 2022-12-21 10:13
Thank you! I'm happy to hear that you managed to customize the planner to meet your needs. In truth the Planner was always intended as an example of how it could be set up of sorts, but then grew to higher complexity as partial planning was added. I'm still considering extending with an Aborted function on the Operator, I think it's a good idea. The version I implement might not meet your requirements, so I'm glad you managed to get your bases covered!
